baseURL = "https://brandon-neth.github.io/ChapelWebsite/"
title = "The Chapel Programming Language"

theme = "hugo-universal-theme"
themesDir = "themes"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[menu]


# Main menu
[[menu.main]]
    name       = "Download"
    identifier = "menu.download"
    url        = "/download"
    weight     = 1

[[menu.main]]
    name       = "Docs"
    identifier = "menu.docs"
    url        = "https://chapel-lang.org/docs/"
    weight     = 3

[[menu.main]]
    name       = "Quickstart Instructions"
    url        = "https://chapel-lang.org/docs/usingchapel/QUICKSTART.html"
    weight     = 1
    parent     = "menu.docs"

[[menu.main]]
    name       = "Language Spec"
    url        = "https://chapel-lang.org/docs/language/spec/index.html"
    weight     = 2
    parent     = "menu.docs"

[[menu.main]]
    name       = "Primers"
    url        = "https://chapel-lang.org/docs/primers/index.html"
    weight     = 3
    parent     = "menu.docs"

[[menu.main]]
    name       = "Developer/Contributor Docs"
    url        = "https://chapel-lang.org/docs/developer/index.html"
    weight     = 4
    parent     = "menu.docs"

[[menu.main]]
    name       = "Technical Notes"
    url        = "https://chapel-lang.org/docs/technotes/index.html"
    weight     = 5
    parent     = "menu.docs"



[[menu.main]]
    name       = "Learn"
    identifier = "menu.learn"
    url        = "/learn"
    weight     = 4

[[menu.main]]
    name       = "Resources"
    identifier = "menu.resources"
    url        = "/resources"
    weight     = 5

[[menu.main]]
    name       = "Papers"
    url        = "/resources#papers"
    weight     = 1
    parent     = "menu.resources"

[[menu.main]]
    name       = "Presentations"
    url        = "/resources#presentations"
    weight     = 2
    parent     = "menu.resources"

[[menu.main]]
    name       = "Tutorials"
    url        = "/resources#tutorials"
    weight     = 3
    parent     = "menu.resources"

[[menu.main]]
    name       = "Community"
    identifier = "section.community"
    url        = "/community"
    weight     = 6

[[menu.main]]
    name       = "Blog"
    identifier = "section.blog"
    url        = "https://chapel-lang.org/blog"
    weight     = 8

[[menu.main]]
    name       = "Try"
    identifier = "section.try"
    url        = "https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY7y4syS1Jz8jSUPFJzcvJ1FMrzi3JSFJU0rSHyUGUw5QA"
    weight     = 7



# Top bar social links menu


[[menu.socials]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/chapel-lang/chapel"
    identifier = "img/socials/github.png"

[[menu.socials]]
    weight = 2
    name = "X (Twitter)"
    url = "https://x.com/ChapelLanguage"
    identifier = "img/socials/twitter.png"

[[menu.socials]]
    weight = 3
    name = "YouTube"
    url="https://www.youtube.com/@ChapelLanguage"
    identifier = "img/socials/youtube.png"

[[menu.socials]]
    weight = 4
    name = "LinkedIn"
    url = "https://www.linkedin.com/company/chapellanguage"
    identifier = "img/socials/linkedin.png"

[[menu.socials]]
    weight = 5
    name = "Mastodon"
    url = "https://mastodon.social/@chapelprogramminglanguage"
    identifier = "img/socials/mastodon.png"

[[menu.socials]]
    weight = 6
    name = "Discourse"
    url = "https://chapel.discourse.group/"
    identifier = "img/socials/discourse.png"

[[menu.socials]]
    weight = 7
    name = "Gitter"
    url = "https://gitter.im/chapel-lang/chapel"
    identifier = "img/socials/gitter.png"

[[menu.socials]]
    weight = 8
    name = "Facebook"
    url = "https://www.facebook.com/ChapelLanguage"
    identifier = "img/socials/facebook.png"

[params]
    version="2.1"
    versionURL="https://chapel-lang.org/blog/posts/announcing-chapel-2.1/"
    mainSections = ["blog"]

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    copyright = ""

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = true

    disabled_logo = false
    logo_text = "Chapel"

    logo = "img/chapel-logo.svg"
    name_logo = "img/ChapelName.png"
    logo_small = "img/chapel-logo.svg"
    contact_url = ""
    address = """
      """

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselApplications]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = false
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.topgrid]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.



[params.applications]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Chapel in Production"
    subtitle = "Check out some of the projects that are using Chapel to accelerate their workflows."


[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = ""
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"


[markup.goldmark.parser.attribute]
    block = true


[[params.quotes]]
    name="Éric Laurendeau"
    title="Professor, Polytechnique Montréal"
    quote="[Chapel] promotes the programming efficiency ... We ask students at the master's degree to do stuff that would take 2 years and they do it in 3 months."

[[params.quotes]]
    name="Tess Hayes"
    title="Developer, Bytoa"
    quote="A lot of the nitty gritty is hidden from you until you need to know it. ... It feels like the complexity grows as you get more comfortable -- rather than being hit with everything at once."

[[params.codes]]
  name="Distributed Hello World"
  default="true"
  code = """
coforall loc in Locales do on loc
  writeln("Hello World from locale ", here.id);
"""


[[params.codes]]
  name="Parallel File IO"
  code="""
forall elements in readDelimited("myFile.txt", t=cityTemperature) {
  /* process data */
}

record cityTemperature: readDeserializable {
  var city: string; // city name
  var temp: real; // temperature
}

proc ref cityTemperature.deserialize(reader: fileReader(?), ref deserializer) throws {
    this.city = reader.readThrough(';', stripSeparator=true);
    this.temp = reader.read(real);
}
"""

[[params.codes]]
  name="1D Heat Diffusion"
  code="""
const fullDomain = {0..<N};
const interior = fullDomain.expand(-1);

var u: [fullDomain] real = 1.0; 
u[N/4..3*N/4] = 2.0; // make the middle a bit hotter

var un = u;

for 1..numSteps {
  un <=> u; // swap the two arrays
  forall i in interior do // shared-memory parallelism
    u[i] = un[i] + alpha * (un[i-1] - 2*un[i] + un[i+1]);  
}
"""

[[params.codes]]
  name="Coral Reef Image Analysis Kernel"
  code="""
proc convolve(InputArr, OutputArr) { //3D Input, 2D Output
 foreach ... {
    tonOfMath();
 }
}

proc main() {
  var InputArr: ...;
  var OutputArr: ...;

  coforall loc in Locales do on loc { // use all nodes in parallel
    coforall gpu in here.gpus do on gpu { // use all GPUs on this node in parallel
      coforall task in 0..#numWorkers { // use numWorkers on this GPU in parallel
        var MyInputArr = InputArr[...]; // high-level slice operations handle data copy
        var MyOutputArr: ...;
        convolve(MyInputArr,MyOutputArr);
        OutputArr[...] = MyOutputArr;
      }
    }
  }
}
"""


